# Generated by Django 3.2.6 on 2024-06-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='original_estimate',
            field=models.IntegerField(null=True),
        ),
    ]
